baseURL = 'https://vubon.me/'
languageCode = 'en-us'
title = 'Vubon Notes'
theme = 'typo'

[outputs]
	home = ['HTML', 'RSS', 'SITEMAP', 'ROBOTS']
	section = ['HTML', 'RSS']

[pagination]
	pagerSize = 5

[params]
	description = 'Engineering notes, tutorials, and experiments.'
	paginationSize = 5

    [params.breadcrumbs]
      enabled = false

	[[params.social]]
		name = 'github'
		url = 'https://github.com/vubon'

    [[params.social]]
        name = 'email'
        url = 'mailto:vubon.roy@gmail.com'

	[[params.menu]]
		name = 'home'
		url = '/'

	[[params.menu]]
		name = 'blog'
		url = '/posts/'

[markup]
	[markup.highlight]
		style = 'dracula'
		lineNos = false
		noClasses = false

	[markup.goldmark.renderer]
		unsafe = true
